apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app
  namespace: testing
  labels: # These labels identify the Deployment itself (optional).
    app: portal-app
spec:
  replicas: 1
  selector:
    matchLabels: # This is how the Deployment selects its Pods.
      app: portal-app
  template:
    metadata:
      labels: # These labels must match the selector.matchLabels above.
        app: portal-app
    spec:
      containers:
      - name: portal-app
        image: jamesw81290/testing:77b13bf
        ports:
        - containerPort: 4001
