apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app
  namespace: default
  labels:
    app: testing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-app
    template:
      metadata:
        labels:
          app: portal-app
      spec:
        containers:
        - name: portal-app
          image: jamesw81290/testing:latest
          ports:
          - containerPort: 8080
