apiVersion: v1
kind: Service
metadata:
  name: portal-app
  namespace: testing
  labels:
    app: portal-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  selector:
    app: portal-app
  type: NodePort
