apiVersion: v1
kind: Service
metadata:
  name: portal-app
  namespace: default
  labels:
    app: portal-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: portal-app
  type: NodePort
