apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "portal.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.applicationPort | quote }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 2 }}
{{- end }}